I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script call
    call intro
  File "game/scripts/pt-0.rpy", line 42, in script
    $ renpy.input("Resultados: " + ", ".join(luckPoints), allow="0123456789")
  File "game/scripts/pt-0.rpy", line 42, in <module>
    $ renpy.input("Resultados: " + ", ".join(luckPoints), allow="0123456789")
TypeError: sequence item 0: expected str instance, int found

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script call
    call intro
  File "game/scripts/pt-0.rpy", line 42, in script
    $ renpy.input("Resultados: " + ", ".join(luckPoints), allow="0123456789")
  File "C:\Program Files (x86)\Renpy\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Renpy\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/pt-0.rpy", line 42, in <module>
    $ renpy.input("Resultados: " + ", ".join(luckPoints), allow="0123456789")
TypeError: sequence item 0: expected str instance, int found

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Sozinho Contra as Chamas 1.0
Wed Jun 11 00:09:23 2025
